quests=['Ankhi','kusum','lubna']
print(f"{quests[0]} is invited to the dinner")
print(f"{quests[1]} is invited to the dinner")
print(f"{quests[2]} is invited to the dinner")
print('I have found a bigger table')
quests.insert(0,'Tifa')
quests.insert(1,'Mim')
quests.append('Sadia')
print(quests)
print(f"{quests[0]} is invited to the dinner")
print(f"{quests[1]} is invited to the dinner")
print(f"{quests[2]} is invited to the dinner")
print(f"{quests[3]} is invited to the dinner")
print(f"{quests[4]} is invited to the dinner")
print(f"{quests[5]} is invited to the dinner")